### PR TITLE
Add version upper bound to architecture support

### PR DESCRIPTION
**Pull request by benmandrew**
OCaml 5.0 does not yet have support for many architectures that are supported by 4.14 and before. `ocaml-version` currently assumes that once a feature is introduced it is never removed, which this PR fixes.

It isn't ideal to continue to expose the `Since` module in the same way, but I don't know what other projects depend on it so I'm staying safe. If it's possible to hide it that would be ideal.

(This is working towards a fix for https://github.com/ocurrent/ocaml-ci/issues/756.)

### CODE REVIEW

**Comment by MisterDA** [comment]
IIRC they're supported in bytecode mode, but there's no native compiler yet.

**Review by kit-ty-kate — CHANGES_REQUESTED** [review]
Yes all those architectures are supported. Only in bytecode-only mode.

**Comment by tmcgilchrist** [comment]
If `ocaml-ci` is the only user of this meta-data about releases then we should just inline it into that project. You can see the rev-deps from opam [here](https://ocaml.org/p/ocaml-version/latest).

A full solution would require handling byte code and native compiler options as pointed out by @kit-ty-kate and @MisterDA.

**Comment by benmandrew** [comment]
Thanks everyone for the info.
For now, this work will be vendored into a branch of OCaml-CI for testing.

**Pull request closed without merging**
